// APP
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'
export const SHOW_MODAL_INPUT_USER = 'APP/SHOW_MODAL_INPUT_USER'
export const HIDE_MODAL_INPUT_USER = 'APP/HIDE_MODAL_INPUT_USER'
export const SHOW_MODAL_ALERT = 'APP/SHOW_MODAL_ALERT'
export const HIDE_MODAL_ALERT = 'APP/HIDE_MODAL_ALERT'

// CHAT
export const ADD_MESSAGE = 'CHAT/ADD_MESSAGE'
export const ON_MESSAGES = 'CHAT/ON_MESSAGES'
export const SHOW_MODAL_MOBILE_CHAT = 'CHAT/SHOW_MODAL_MOBILE_CHAT'
export const HIDE_MODAL_MOBILE_CHAT = 'CHAT/HIDE_MODAL_MOBILE_CHAT'

// SETTINGS SPACESHIP
export const SHOW_MODAL_SETTINGS_SPACESHIP =
  'CHAT/SHOW_MODAL_SETTINGS_SPACESHIP'
export const HIDE_MODAL_SETTINGS_SPACESHIP =
  'CHAT/HIDE_MODAL_SETTINGS_SPACESHIP'
// SETTINGS ROOM
export const SHOW_MODAL_SETTINGS_ROOM = 'CHAT/SHOW_MODAL_SETTINGS_ROOM'
export const HIDE_MODAL_SETTINGS_ROOM = 'CHAT/HIDE_MODAL_SETTINGS_ROOM'

// USERS
export const ON_USERS = 'USERS/ON_USERS'
// USER
export const EMIT_USER = 'USER/EMIT_USER'
export const ON_USER = 'USER/ON_USER'
// ROOMS
export const WRITE_ROOMS = 'ROOMS/WRITE_ROOMS'
export const ADD_ROOM = 'ROOMS/ADD_ROOM'
export const REMOVE_ROOM = 'ROOMS/REMOVE_ROOM'

// ROOM
export const WRITE_ROOM_ID = 'ROOM/WRITE_ROOM_ID'
export const WRITE_ROOM_CONFIG = 'ROOM/WRITE_ROOM_CONFIG'
export const SET_YOU_IS_CREATOR_ROOM = 'ROOM/SET_YOU_IS_CREATOR_ROOM'
export const SET_CURRENT_ROOM = 'ROOM/SET_CURRENT_ROOM'
export const SET_YOU_IS_VISITOR = 'ROOM/SET_YOU_IS_VISITOR'
export const SET_USERS_CURRENT_ROOM = 'ROOM/SET_USERS_CURRENT_ROOM'
export const ADD_USER_CURRENT_ROOM = 'ROOM/ADD_USER_CURRENT_ROOM'
export const REMOVE_USER_CURRENT_ROOM = 'ROOM/REMOVE_USER_CURRENT_ROOM'
export const RESET_CURRENT_ROOM = 'ROOM/RESET_CURRENT_ROOM'

// export const ON_CREATED_ROOM = 'ROOM/ON_CREATED_ROOM';
// export const ON_ENTER_IN_ROOM = 'ROOM/ON_ENTER_IN_ROOM';
// export const ON_LEAVE_FROM_ROOM = 'ROOM/ON_LEAVE_FROM_ROOM';
// export const ON_START_GAME = 'ROOM/ON_START_GAME';

// export const FETCH_POSTS = 'POST/FETCH_POSTS';
// export const REQUEST_POSTS = 'POST/REQUEST_POSTS';
// export const SHOW_LOADER = 'APP/SHOW_LOADER';
// export const HIDE_LOADER = 'APP/HIDE_LOADER';
// export const SHOW_ALERT = 'APP/SHOW_ALERT';
// export const HIDE_ALERT = 'APP/HIDE_ALERT';
