// APP
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
export const SHOW_MODAL_INPUT_USER = 'APP/SHOW_MODAL_INPUT_USER';
export const HIDE_MODAL_INPUT_USER = 'APP/HIDE_MODAL_INPUT_USER';
// CHAT
export const ADD_MESSAGE = 'CHAT/ADD_MESSAGE';
export const ON_MESSAGES = 'CHAT/ON_MESSAGES';
// USERS
export const ON_USERS = 'USERS/ON_USERS';
// USER
export const EMIT_USER = 'USER/EMIT_USER';
export const ON_USER = 'USER/ON_USER';
// ROOMS
export const ON_ROOMS = 'ROOMS/ON_ROOMS';
// ROOM
export const EMIT_CREATED_ROOM = 'ROOM/EMIT_CREATED_ROOM';
export const ON_CREATED_ROOM = 'ROOM/ON_CREATED_ROOM';

export const EMIT_ENTER_IN_ROOM = 'ROOM/EMIT_ENTER_IN_ROOM';
export const ON_ENTER_IN_ROOM = 'ROOM/ON_ENTER_IN_ROOM';

export const EMIT_LEAVE_FROM_ROOM = 'ROOM/EMIT_LEAVE_FROM_ROOM';
export const ON_LEAVE_FROM_ROOM = 'ROOM/ON_LEAVE_FROM_ROOM';

export const EMIT_START_GAME = 'ROOM/EMIT_START_GAME';
export const ON_START_GAME = 'ROOM/ON_START_GAME';

// export const FETCH_POSTS = 'POST/FETCH_POSTS';
// export const REQUEST_POSTS = 'POST/REQUEST_POSTS';
// export const SHOW_LOADER = 'APP/SHOW_LOADER';
// export const HIDE_LOADER = 'APP/HIDE_LOADER';
// export const SHOW_ALERT = 'APP/SHOW_ALERT';
// export const HIDE_ALERT = 'APP/HIDE_ALERT';
